# Generated by Django 2.1 on 2019-05-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='phone',
            field=models.CharField(default='01234567890', max_length=11),
        ),
    ]
