# Generated by Django 2.1 on 2019-05-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detials', models.CharField(max_length=600)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target', models.FloatField()),
                ('achived', models.FloatField()),
                ('isFeatured', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('isAdmin', models.BooleanField(default=0)),
                ('phone', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
                ('fb_account', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=60)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funding.Project_Image'),
        ),
    ]
