# Generated by Django 2.1 on 2019-05-11 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0003_auto_20190508_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='img',
        ),
        migrations.AddField(
            model_name='project_image',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funding.Project'),
        ),
    ]
