# Generated by Django 2.2.1 on 2019-05-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0004_auto_20190510_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='fb_account',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
