# Generated by Django 2.2.1 on 2019-05-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0005_auto_20190513_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fb_account',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
